version: "3"
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: shellTest
        working_dir: /home/devuser/src
        user: devuser
        volumes:
            - ../:/home/devuser/src
            - ~/.ssh/id_rsa:/home/devuser/.ssh/id_rsa
        tty: true
